// Pulled from the MDN content source: https://github.com/mdn/content/tree/main/files/en-us/web/html/reference
// Last pull was April 2026.

export const ELEMENTS = {
  "html": [],
  "base": ["href", "target"],
  "head": [],
  "link": [
    "href",
    "crossorigin",
    "integrity",
    "media",
    "rel",
    "sizes",
    "type",
    "as",
    "fetchpriority",
  ],
  "meta": ["charset", "content", "http-equiv"],
  "style": ["media", "type"],
  "title": [],
  "body": ["background", "bgcolor"],
  "address": [],
  "article": [],
  "aside": [],
  "footer": [],
  "header": [],
  "h1": [],
  "h2": [],
  "h3": [],
  "h4": [],
  "h5": [],
  "h6": [],
  "hgroup": [],
  "main": [],
  "nav": [],
  "section": [],
  "search": [],
  "blockquote": ["cite"],
  "dd": [],
  "div": [],
  "dl": [],
  "dt": [],
  "figcaption": [],
  "figure": [],
  "hr": ["align", "color", "noshade", "size", "width"],
  "li": ["value"],
  "menu": [],
  "ol": ["reversed", "start", "type"],
  "p": [],
  "pre": [],
  "ul": [],
  "a": [
    "href",
    "download",
    "hreflang",
    "media",
    "ping",
    "rel",
    "shape",
    "target",
    "type",
  ],
  "abbr": [],
  "b": [],
  "bdi": [],
  "bdo": [],
  "br": [],
  "cite": [],
  "code": [],
  "data": ["value"],
  "dfn": [],
  "em": [],
  "i": [],
  "kbd": [],
  "mark": [],
  "q": ["cite"],
  "rp": [],
  "rt": [],
  "ruby": [],
  "s": [],
  "samp": [],
  "small": [],
  "span": [],
  "strong": [],
  "sub": [],
  "sup": [],
  "time": ["datetime"],
  "u": [],
  "var": [],
  "wbr": [],
  "area": [
    "alt",
    "coords",
    "download",
    "href",
    "ping",
    "rel",
    "shape",
    "target",
  ],
  "audio": [
    "autoplay",
    "controls",
    "crossorigin",
    "loop",
    "muted",
    "preload",
    "src",
  ],
  "img": [
    "alt",
    "crossorigin",
    "decoding",
    "elementtiming",
    "fetchpriority",
    "height",
    "ismap",
    "loading",
    "longdesc",
    "src",
    "srcset",
    "usemap",
    "width",
  ],
  "map": ["name"],
  "track": ["default", "kind", "label", "srclang", "src"],
  "video": [
    "autoplay",
    "controls",
    "crossorigin",
    "height",
    "playsinline",
    "poster",
    "preload",
    "src",
    "width",
    "muted",
    "loop",
  ],
  "embed": ["height", "src", "type", "width"],
  "fencedframe": [],
  "iframe": [
    "allow",
    "csp",
    "height",
    "name",
    "referrerpolicy",
    "sandbox",
    "src",
    "srcdoc",
    "width",
  ],
  "object": [
    "data",
    "form",
    "height",
    "name",
    "type",
    "usemap",
    "width",
    "border",
  ],
  "picture": [],
  "source": ["src", "srcset", "type", "media", "sizes", "as"],
  "svg": [],
  "math": [],
  "canvas": ["height", "width"],
  "noscript": [],
  "script": [
    "async",
    "charset",
    "crossorigin",
    "defer",
    "fetchpriority",
    "integrity",
    "language",
    "src",
    "type",
  ],
  "del": ["cite", "datetime"],
  "ins": ["cite", "datetime"],
  "caption": ["align"],
  "col": ["align", "bgcolor", "char", "charoff", "span", "valign", "width"],
  "colgroup": [
    "align",
    "bgcolor",
    "char",
    "charoff",
    "span",
    "valign",
    "width",
  ],
  "table": [
    "align",
    "bgcolor",
    "border",
    "cellpadding",
    "cellspacing",
    "frame",
    "rules",
    "summary",
    "width",
  ],
  "tbody": ["align", "bgcolor", "char", "charoff", "valign"],
  "td": [
    "align",
    "bgcolor",
    "colspan",
    "headers",
    "rowspan",
    "scope",
    "valign",
    "width",
  ],
  "tfoot": ["align", "bgcolor", "char", "charoff", "valign"],
  "th": [
    "align",
    "bgcolor",
    "colspan",
    "headers",
    "rowspan",
    "scope",
    "valign",
    "width",
  ],
  "thead": ["align", "bgcolor", "char", "charoff", "valign"],
  "tr": ["align", "bgcolor", "char", "charoff", "valign"],
  "button": [
    "autofocus",
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "name",
    "type",
    "value",
  ],
  "datalist": [],
  "fieldset": ["disabled", "form", "name"],
  "form": [
    "accept-charset",
    "action",
    "autocomplete",
    "enctype",
    "method",
    "name",
    "novalidate",
    "target",
  ],
  "input": [
    "accept",
    "alt",
    "autocomplete",
    "autocorrect",
    "autofocus",
    "capture",
    "checked",
    "dirname",
    "disabled",
    "form",
    "formaction",
    "formenctype",
    "formmethod",
    "formnovalidate",
    "formtarget",
    "height",
    "list",
    "max",
    "maxlength",
    "minlength",
    "min",
    "multiple",
    "name",
    "pattern",
    "placeholder",
    "readonly",
    "required",
    "size",
    "src",
    "step",
    "type",
    "value",
    "width",
    "alpha",
    "colorspace",
    "entrymode",
  ],
  "label": ["for", "form"],
  "legend": ["align"],
  "meter": ["high", "low", "max", "min", "optimum", "value"],
  "optgroup": ["disabled", "label"],
  "option": ["disabled", "label", "selected", "value"],
  "output": ["for", "form", "name"],
  "progress": ["max", "value"],
  "select": [
    "autofocus",
    "disabled",
    "form",
    "multiple",
    "name",
    "required",
    "size",
  ],
  "selectedcontent": [],
  "textarea": [
    "autocorrect",
    "autofocus",
    "cols",
    "dirname",
    "disabled",
    "enterkeyhint",
    "form",
    "inputmode",
    "maxlength",
    "minlength",
    "name",
    "placeholder",
    "readonly",
    "required",
    "rows",
    "spellcheck",
    "wrap",
  ],
  "details": ["open"],
  "dialog": ["open"],
  "geolocation": [],
  "summary": [],
  "slot": ["name"],
  "template": [],
};

export const VOID_ELEMENT_LIST = [
  "area",
  "base",
  "br",
  "col",
  "embed",
  "hr",
  "img",
  "input",
  "link",
  "meta",
  "param",
  "source",
  "track",
  "wbr",
];

export const GLOBAL_ATTRIBUTE_LIST = [
  "accesskey",
  "anchor",
  "autocapitalize",
  "autocorrect",
  "autofocus",
  "class",
  "contenteditable",
  "dir",
  "draggable",
  "enterkeyhint",
  "exportparts",
  "hidden",
  "id",
  "inert",
  "inputmode",
  "is",
  "itemid",
  "itemprop",
  "itemref",
  "itemscope",
  "itemtype",
  "lang",
  "nonce",
  "part",
  "popover",
  "role",
  "slot",
  "spellcheck",
  "style",
  "tabindex",
  "title",
  "translate",
  "virtualkeyboardpolicy",
  "writingsuggestions",
  "xml:lang",
  "xml:base",
  "onabort",
  "onanimationcancel",
  "onanimationend",
  "onanimationiteration",
  "onanimationstart",
  "onauxclick",
  "onbeforeinput",
  "onbeforematch",
  "onbeforetoggle",
  "onblur",
  "oncancel",
  "oncanplay",
  "oncanplaythrough",
  "onchange",
  "onclick",
  "onclose",
  "oncommand",
  "oncontentvisibilityautostatechange",
  "oncontextlost",
  "oncontextmenu",
  "oncontextrestored",
  "oncopy",
  "oncuechange",
  "oncut",
  "ondblclick",
  "ondrag",
  "ondragend",
  "ondragenter",
  "ondragleave",
  "ondragover",
  "ondragstart",
  "ondrop",
  "ondurationchange",
  "onemptied",
  "onended",
  "onerror",
  "onfocus",
  "onfocusin",
  "onfocusout",
  "onformdata",
  "onfullscreenchange",
  "onfullscreenerror",
  "ongesturechange",
  "ongestureend",
  "ongesturestart",
  "ongotpointercapture",
  "oninput",
  "oninvalid",
  "onkeydown",
  "onkeypress",
  "onkeyup",
  "onload",
  "onloadeddata",
  "onloadedmetadata",
  "onloadstart",
  "onlostpointercapture",
  "onmousedown",
  "onmouseenter",
  "onmouseleave",
  "onmousemove",
  "onmouseout",
  "onmouseover",
  "onmouseup",
  "onmousewheel",
  "onpaste",
  "onpause",
  "onplay",
  "onplaying",
  "onpointercancel",
  "onpointerdown",
  "onpointerenter",
  "onpointerleave",
  "onpointermove",
  "onpointerout",
  "onpointerover",
  "onpointerrawupdate",
  "onpointerup",
  "onprogress",
  "onratechange",
  "onreset",
  "onresize",
  "onscroll",
  "onscrollend",
  "onscrollsnapchange",
  "onscrollsnapchanging",
  "onsecuritypolicyviolation",
  "onseeked",
  "onseeking",
  "onselect",
  "onselectionchange",
  "onselectstart",
  "onslotchange",
  "onstalled",
  "onsubmit",
  "onsuspend",
  "ontimeupdate",
  "ontoggle",
  "ontouchcancel",
  "ontouchend",
  "ontouchmove",
  "ontouchstart",
  "ontransitioncancel",
  "ontransitionend",
  "ontransitionrun",
  "ontransitionstart",
  "onvolumechange",
  "onwaiting",
  "onwebkitmouseforcechanged",
  "onwebkitmouseforcedown",
  "onwebkitmouseforceup",
  "onwebkitmouseforcewillbegin",
  "onwheel",
];
