#!/bin/bash

set -euo pipefail

CUTOUT_MODEL=${1:-"mlx-community/Qwen3.6-35B-A3B-mxfp8"}

brew bundle --quiet
mlx_lm.chat \
  --model "${CUTOUT_MODEL}" \
  --max-tokens 65536 \
  --system-prompt "$(cat ./SYSTEM.md)"
