name: Publish JSR
on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

env:
  TAG_NAME: ${{ github.event.release.tag_name }}

jobs:
  publish-jsr:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.TAG_NAME }}

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Get Package Directory
        id: package
        run: echo "directory=${TAG_NAME%/*}" >> $GITHUB_OUTPUT

      - name: Publish JSR
        working-directory: ${{ steps.package.outputs.directory }}
        run: deno publish
