name: Create Draft Release

on:
  workflow_dispatch:
    inputs:
      directory:
        type: choice
        required: true
        description: The workspace directory to publish.
        options: [jsx]

      version:
        type: string
        required: true
        description: A valid semver string (e.g. `0.0.1` or `1.2.3-alpha.0`)

permissions:
  contents: write

env:
  VERSION: ${{ inputs.version }}
  ROOT: ${{ inputs.directory }}
  TAG_NAME: ${{ inputs.directory }}@${{ inputs.version }}

jobs:
  release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Inputs
        run: |
          D='0|[1-9][0-9]*'
          PW='[0-9]*[a-zA-Z-][0-9a-zA-Z-]*'
          MW='[0-9a-zA-Z-]+'
          if [[ "${VERSION}" =~ ^($D)\.($D)\.($D)(-(($D|$PW)(\.($D|$PW))*))?(\+($MW(\.$MW)*))?$ ]]; then
            exit 0
          else
            echo "Input version '${VERSION}' is not a valid semver string!"
            exit 1
          fi
      
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      
      - name: Validate Tag
        run: |
          if git rev-parse "refs/tags/${TAG_NAME}" >/dev/null 2>&1; then
            echo "Tag '${TAG_NAME}' already exists!"
            exit 1
          fi
      
      - name: Commit Version
        # TODO: it's jsonc, not json
        run: |
          tmp="$(mktemp)"
          jq --arg v "${VERSION}" '.version=$v' "${ROOT}/deno.jsonc" > "$tmp"
          mv "$tmp" "${ROOT}/deno.jsonc"
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add "${ROOT}/deno.jsonc"
          git commit -m "${TAG_NAME}"
          git tag "${TAG_NAME}"
      
      - name: Push
        # TODO: bot permissions?
        run: |
          git push origin HEAD
          git push origin "${TAG_NAME}"

  draft-release:
    needs: release-tag
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ env.TAG_NAME }}
     
      - name: Create Draft Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: "@cutout/${{ env.TAG_NAME }}"
          draft: true
          generate_release_notes: true
